language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install coveralls
  - pip install coverage

script: "coverage run --source=pymp setup.py test"

after_success:
  - coveralls
